# OpenAI

openai_api_key: sk-proj-4VP8VgGiCGWSIh31ID57T3BlbkFJ1OTYWxFTGn4KlcRd4965

openai_base_url: null

openai_model: null

# Azure OpenAI

azure_api_key: null

azure_endpoint: null

azure_api_version: null

azure_model: null
